language: csharp
mono: none

branches:
  except:
    - /^untagged/
    - /^nightly/

git:
  depth: 2
  quiet: true
  symlinks: true

jobs:
  include:
    - stage: "Compile for amd64 Windows"
      os: windows
      script:
        - choco install dotnetcore-sdk
        - dotnet --version
        - dotnet restore
        - dotnet publish -r win-x64 --configuration Release -p:PublishSingleFile=true
      deploy: &deploy_base
        provider: releases
        api_key:
          secure: LBMhhnL69Uh0jffdPoDCN7YUkj2azj6YUjgxBVgZ2OOtW4IPfpo8f4hwN/HjF5Sf+LHv4RYxvWm5sRKBtftWF90hMjFzeKJ16agnjIN/eP/tcTvSutXyn25oYYqyJOMs/wMGhcAelb0KD9s6h7JIRsG09f5DL8ONlMpzzqM+7AiQeIohJ/RPF7on2flUqywpRYHPfC/dVHxSj6QKQRGiOSUd8r15W6CmQsEknuidMzW8noZImClr+3KUeYBDS0Khn91iol2bAI3RUQ/TTH2G2he1dqXZZ2OH2oxdYtCjIcV1EyMDPPOrdyZ3/14BSaXveqOp2JBMJtZt2fkvLq2zaBTh2JBPAWM3j+tFukagwWhfLihe/Wq4NDjpJUjdTK2n5JTtqb1R58pIZNhFo0Mb8dkcrL/vrWw10aOo4snZNOTmRvcLM9J1G2bdy/uNZzSzCzXEIQEW58FUVeuhjpFDuYNRbEVyA88IkymQJI6TUBSx3zK4W6DmWNc1UslP6g4BdjOOK9d182at9Z9ZnLaxvYaNECfNxlu+fAfcJepf3StSBRIiXyRbCM8GCzLnKIOR7JxzPoY3BDFnSAb6dV84Fk6QXirPBbsr/ZGcJBiqCqWBTU+YIwM20pDuRyAkRMfFDMqCs5xw7JFe5pzdgUA/C3gSlJgUhT0a67/iNbeK5vQ=
        file: "ImagePoster4DTF/bin/Release/netcoreapp3.1/win-x64/publish/ImagePoster4DTF.exe"
        draft: true
        tag_name: $TRAVIS_TAG
        target_commitish: $TRAVIS_COMMIT
        name: "[$TRAVIS_TAG] Nightly release for $TRAVIS_COMMIT"
        prerelease: true
        overwrite: true
        skip_cleanup: true
    - stage: "Compile for amd64 macOS"
      os: osx
      osx_image: xcode11.5
      dotnet: 3.1.301
      script:
        - dotnet restore
        - dotnet publish -r osx-x64 --configuration Release -p:PublishSingleFile=true
        - "cp ./ImagePoster4DTF/bin/Release/netcoreapp3.1/osx-x64/publish/ImagePoster4DTF ./ImagePoster4DTF_macOS"
      deploy:
        <<: *deploy_base
        file: "ImagePoster4DTF_macOS"
    - stage: "Compile for amd64 GNU/Linux and deploy GitHub Release"
      os: linux
      dist: bionic
      dotnet: 3.1.301
      script:
        - dotnet restore
        - dotnet publish -r linux-x64 --configuration Release -p:PublishSingleFile=true
        - "cp ./ImagePoster4DTF/bin/Release/netcoreapp3.1/linux-x64/publish/ImagePoster4DTF ./ImagePoster4DTF_linux"
      deploy:
        <<: *deploy_base
        draft: false
        file: "ImagePoster4DTF_linux"

before_deploy:
  - git config --local user.name "Artoria Pendragon"
  - git config --local user.email "saber-nyan@ya.ru"
  - export TRAVIS_TAG="nightly-$TRAVIS_BUILD_NUMBER"
  - echo "Tagging commit ${TRAVIS_COMMIT} with tag ${TRAVIS_TAG}"
  - git tag "$TRAVIS_TAG" "$TRAVIS_COMMIT"
